# Generated by Django 5.1.6 on 2025-03-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Insira seu nome.', max_length=100, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
