# Generated by Django 5.1.6 on 2025-03-18 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Insira seu nome.', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(default='teste@gmail.com', help_text='Insira seu e-mail', max_length=254, unique=True, verbose_name='E-mail')),
                ('generos', models.CharField(choices=[('MAN', 'Homem'), ('WOMAN', 'Mulher'), ('N_BINARY', 'Não Binário'), ('N_INFORM', 'Não informado')], help_text='Selecione seu genero', max_length=10, verbose_name='Genero')),
                ('CPF', models.IntegerField(help_text='Insira seu CPF', validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)], verbose_name='CPF')),
                ('senha', models.CharField(help_text='Insira sua senha', max_length=20, verbose_name='Senha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
