# Generated by Django 5.1.6 on 2025-05-19 22:29

import aula.validators.cod
import aula.validators.funcoes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('data_publicao', models.DateField(help_text='Data de Publicação', verbose_name='Data de Publicação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('edition', models.IntegerField(help_text='Edição', verbose_name='Edição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), aula.validators.cod.CodValidator('4444444444'), aula.validators.funcoes.validate_par])),
                ('nome', models.CharField(help_text='Nome', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('data_aniversario', models.DateField(help_text='Data de Anivesário', verbose_name='Data de Aniversário')),
                ('cpf', models.CharField(help_text='CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('email', models.EmailField(help_text='E-mail', max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(help_text='CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('numer', models.CharField(help_text='Número do passaporte', max_length=14, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Passport')),
                ('data_expedicao', models.DateField(help_text='Data de expedição', verbose_name='Data emissão')),
                ('expiration_date', models.DateField(help_text='Data de expiração', verbose_name='Data Vencimento')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.article')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.magazine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='aula.Publication', to='aula.magazine'),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.reporter'),
        ),
    ]
